ALTER TABLE program
    ADD COLUMN IF NOT EXISTS kode_opd VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tahun INTEGER;

ALTER TABLE kegiatan
    ADD COLUMN IF NOT EXISTS kode_opd VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tahun INTEGER;

ALTER TABLE subkegiatan
    ADD COLUMN IF NOT EXISTS kode_opd VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tahun INTEGER;
