ALTER TABLE rencana_aksi
ADD COLUMN id_rekin VARCHAR(255),
ADD COLUMN kode_opd VARCHAR(255),
ADD COLUMN id_pegawai VARCHAR(255),
ADD COLUMN created_by VARCHAR(255),
ADD COLUMN bulan INTEGER,
ADD COLUMN tahun INTEGER;